image: eclipse-temurin:21

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew build
  artifacts:
    paths:
      - lwjgl3/build/libs/

test-job:
  stage: test
  script:
    - chmod +x ./gradlew
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - core/build/reports/tests/
